fun main(){
    println("Enter your Enrollment number:")
    var ennumber= readLine()
    println("Enter your Name:")
    var name= readLine()
    println("Enter your Branch:")
    var branch= readLine()
    println("Enter your Class:")
    var cls= readLine()
    println("Enter your Batch:")
    var btc= readLine()
    println("Enter your college name:")
    var clg= readLine()
    println("Enter your University name:")
    var unv= readLine()
    println("Enter your Age:")
    var age= readLine()

    println("**********************")
    println("Student's Data")
    println("Enrollment no.:$ennumber")
    println("Name:$name")
    println("Branch:$branch")
    println("Class:$cls")
    println("Batch:$btc")
    println("College:$clg")
    println("University:$unv")
    println("Age:$age")
}

